name: 'ipfs-php'

services:
  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs
    ports:
      - target: 4001
        published: 4001
        protocol: tcp
      - target: 5001
        published: 5001
        protocol: tcp
      - target: 8080
        published: 8088
        protocol: tcp

networks:
  default:
    name: 'ipfs-php-network'
